name: automerge
on:
  pull_request:
    types:
      - opened
      - synchronize
  schedule:
    - cron: "0 2 * * 1"  # Weekly schedule for checking Dependabot PRs
  workflow_dispatch:  # Allow manual triggering of this workflow

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions: # Grant permission to modify pull requests
      pull-requests: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensure the repository is checked out

      - name: Automate Merge
        id: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          merge_method: "squash"  # Optional: Specify merge method (merge, squash, or rebase)

      - name: Check Merge Result
        run: |
          echo "Automerge output: ${{ steps.automerge.outputs.result }}"
          echo "Automerge action status: ${{ steps.automerge.outcome }}"