name: Auto-merge Dependabot updates
on:
  pull_request:
    types:
      - opened
      - synchronize
  schedule:
    - cron: "0 2 * * 1"  # Weekly schedule for checking Dependabot PRs
  workflow_dispatch:  # Allow manual triggering of this workflow

permissions:
  pull-requests: write  # Grant permission to modify pull requests
  contents: read  # Allow reading the repository contents

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
